### ISSUE TITLE
trying to upgrade to newest version

### ISSUE THREAD

**Issue by piecesnbits** [n1crack/datatables#40]
I was still using the old version of you api. but need to update due to "out of memory" errors due to the count() function in mysql.php. However I get errors...
```Notice: Undefined offset: 7 in /home/eosdac/eosdac-token-explorer/api/vendor2/ozdemir/datatables/src/ColumnCollection.php on line 156

Notice: Undefined offset: 8 in /home/eosdac/eosdac-token-explorer/api/vendor2/ozdemir/datatables/src/ColumnCollection.php on line 156

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 't.account_action_seq'; this is incompatible with sql_mode=only_full_group_by in /home/eosdac/eosdac-token-explorer/api/vendor2/ozdemir/datatables/src/DB/MySQL.php:70 Stack trace: #0 /home/eosdac/eosdac-token-explorer/api/vendor2/ozdemir/datatables/src/DB/MySQL.php(70): PDOStatement->execute(Array) #1 /home/eosdac/eosdac-token-explorer/api/vendor2/ozdemir/datatables/src/Datatables.php(163): Ozdemir\Datatables\DB\MySQL->count(Object(Ozdemir\Datatables\Query)) #2 /home/eosdac/eosdac-token-explorer/api/vendor2/ozdemir/datatables/src/Datatables.php(142): Ozdemir\Datatables\Datatables->setResponseData() #3 /home/eosdac/eosdac-token-explorer/api/explorer_table_api2.php(46): Ozdemir\Datatables\Datatables->generate() #4 {main} thrown in /home/eosdac/eosdac-token-explorer/api/vendor2/ozdemir/datatables/src/DB/MySQL.php on line 70```

**Comment by n1crack** [comment]
hey thank you for using the library.

the error is related to sql query. 

`SELECT list contains nonaggregated column 't.account_action_seq'`

Can you provide your full query?

**Comment by piecesnbits** [comment]
sure but it did work with a previous version of your code.
`SELECT account_action_seq, _from, _to, _quantity, _symbol, _memo, txid, block_num, block_time FROM transfers ORDER BY account_action_seq DESC`

**Comment by piecesnbits** [comment]
personally I think there is something wrong with my query parameters. I'm parsing/constructing them myself. so there must be something in your new version changed that broke it.

**Comment by piecesnbits** [comment]
hey the update fixed something but still got the ColumnColections error
![image](https://user-images.githubusercontent.com/44613132/48370931-d5331380-e6ba-11e8-81a6-c8f72b7ae63f.png)

**Comment by n1crack** [comment]
can you share the header part of your ajax request ?
There is something wrong, couldn't figure it out yet.

<img width="898" alt="ekran resmi 2018-11-12 22 51 16" src="https://user-images.githubusercontent.com/712404/48371680-880c6d00-e6cd-11e8-9cce-8575b3400130.png">

**Comment by piecesnbits** [comment]
![image](https://user-images.githubusercontent.com/44613132/48372102-d6197480-e6bd-11e8-87f8-ca6b015005dd.png)

btw if I disable errors it seems to work so the errors are not critical.

**Comment by n1crack** [comment]
as i thought, your table has only 6 column right? but it seems your sql has 8 columns.

**Comment by piecesnbits** [comment]
yes but that did work in your previous version.

**Comment by n1crack** [comment]
ok fixed. you can try it with 2.0.3 in a couple minutes

**Comment by piecesnbits** [comment]
fix confirmed! thank you very much, you saved me a lot of work! In fact we're not using jquery datatables at all. I wrote an adapter for vue quasar datatables to work with your lib. peace!
